rm pqjs/pq_strnfy_web.js
pq_webpage_compress home.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress user_sum.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress dash_sdas.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress link_util_app.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress ses_sessions.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress shadow_session_watch.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress ses_sources.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress shadow_server_watch.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress shadow_url_watch.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress ses_dest.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress ses_app.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress ses_serv.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress traffic_diag.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress rule_dest.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress rule_url.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress rule_app.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress rule_serv.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress obj_sched.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress obj_admin_pipes.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress obj_user_pipes.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress bw_history.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress profile_ips.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress profiles.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress billing.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress management.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress high_availability.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress maintenance.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress system_update.html >> pqjs/pq_strnfy_web.js
pq_webpage_compress ele_pqpie_label.html >> pqjs/pq_strnfy_web.js

cd pqjs/ && ./cmpressPq_js.sh 
cd ../pqcss/ && ./cmppqcss.sh 